on:
  release:
    types: [published]
jobs:
  build-and-release:
    name: Build and release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: rustup update
      - run: cargo build --release
      - name: Archive binaries
        run: tar -czvf linux-binaries.tar.gz -C ./target/release/ .
      - name: Upload binaries to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./linux-binaries.tar.gz
          asset_name: linux-binaries.tar.gz
          asset_content_type: application/gzip
